sudo: requierd
services:
 - docker

before_install:
 - docker build -t pj/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true pj/react-test npm test

after_script:
 - docker build -t pj/fib-client ./client
 - docker build -t pj/fib-server ./server
 - docker build -t pj/fib-worker ./worker
 - docker build -t pj/fib-nginx ./nginx
 - echo "$DOCKER_PASSWORD" | docker_login -u "$DOCKER_ID" --password-stdin
 - docker push pj/fib-client
 - docker push pj/fib-server
 - docker push pj/fib-worker
 - docker push pj/fib-nginx