sudo: requierd
services:
 - docker

before_install:
 - docker build -t piotr04j/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true piotr04j/react-test npm test

after_script:
 - docker build -t piotr04j/fib-client ./client
 - docker build -t piotr04j/fib-server ./server
 - docker build -t piotr04j/fib-worker ./worker
 - docker build -t piotr04j/fib-nginx ./nginx
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push piotr04j/fib-client
 - docker push piotr04j/fib-server
 - docker push piotr04j/fib-worker
 - docker push piotr04j/fib-nginx